# Configure.
env:
  - DOCKER_TAG=centos6
  - DOCKER_TAG=centos7
  - DOCKER_TAG=fedora22
  - DOCKER_TAG=fedora23
  - DOCKER_TAG=fedora24
  - DOCKER_TAG=fedora25
  - DOCKER_TAG=fedoraRawhide
services: [docker]
sudo: required

# Run.
before_install: hooks/post_checkout
install: docker build . -t local
script:
  - mkdir out

  - docker run -v $PWD/tests:/SPECS local  # Test unmounted output volumes.
  - docker run -v $PWD/tests:/SPECS -v $PWD/out:/SRPMS -v $PWD/out:/RPMS local
  - ls -la out/*
  - compgen -G "out/smtpping-1.1.3-1.*.src.rpm"
  - compgen -G "out/x86_64/smtpping-1.1.3-1.*.x86_64.rpm"

  - rm -r out/x86_64; docker run -v $PWD/out:/SRPMS local
  - docker run -v $PWD/out:/SRPMS -v $PWD/out:/RPMS local
  - ls -la out/*
  - compgen -G "out/smtpping-1.1.3-1.*.src.rpm"
  - compgen -G "out/x86_64/smtpping-1.1.3-1.*.x86_64.rpm"
